var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                   xxx                                          ",
   "                                  xx!xx                                         ",
   "                                  x!!!x                                         ",
   "                                  xx!xx                                         ",
   "                                   xvx          o        yyyy     xxx           ",
   "                                                                 xx!xx          ",
   "                                               xxxx              x!!!x          ",
   "                                                                 xx!xx          ",
   "                                         xxxx                     xvx           ",+
   "                                                                            xx  ",
   "  xx                                                                         x  ",
   "  x           o         o                     yyyy      f                    x  ",
   "  x                                                                        o x  ",
   "  x                     o     xxxxx                  xxxxxxx                 x  ",
   "  x  @                        x   x b                x     x                 x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "             x  x                                                               ",
   "             x!!x                                                               ",
   "             x!!x                                                               ",
   "             xxxx                                                               ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "             xxxxx     xxxxx                                                                                ",
   "            xxx!xxx   xxx!xxx                                                                               ",
   "            xx!!!xx   xx!!!xx                                                                               ",
   "             xx!xx     xx!xx                                             f                                  ",
   "              xvx       xvx                                                                                 ",
   "                                                                       xxxxxx                               ",
   "                                                                    xx                                      ",
   "                                                                 xx                                       x ",
   "           o        o         o                              xx                                           x ",
   "                                                                                                          x ",
   "          xxxxxxxxxxxxxxxxxxxxxxx                                            xxxxxxxxxxxx         o       x ",
   "  @       x                     x b      xxxxxxxxxx                          x          x                 x ", 
   "xxxxxxxxxxx                     xxxxxxxxxx        xxxxxxxxx!!!!!xxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxx",
   "                                                                                                    "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "             o                                                           xxx                                  ",
   " @                                                                      xx!xx                                 ",
   "xxxx      xxxxxxx!!                                                     x!!!x                                 ",
   "   x b    x     x!!!xxx             f                                    xvx                                  ",
   "   xxxxxxxx     x!!!!!!!!!!xxx                                                                                ",
   "                x!!!!!!!!!!!!!!!!!!xxx                                                                        ",
   "                xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                  ",
   "                                           x                                                               x  ",
   "                                           x b             xxxxxx                                          x  ",
   "                                           xxxxxxxxxxxxxxxxx    x                                          x  ",
   "                                                                x        o       xxxxxxxxxxx            o  x  ",
   "                                                                x                x         x b             x  ",
   "                                                                xxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                           xxx                                                                                ",
   "                          xx!xx                                                                               ",
   "                          x!!!x                                   f      xxx                                  ",
   "                           xvx                                                                                ",
   "                                                               x!!!!x                 o                       ",
   "                                                    o      xxxxxxxxxx                                         ",
   "                                                                                xxxx b    xxxx                ",
   "                                                  xxxxx                         xxxxxxxxxxxxxx                ",
   "                                                                                                              ",
   "                                          xxxxx                        o                                      ",
   "x                                                                                                             ",
   
   "x                                                                                                         x   ",
   "x                         xxxxxxxxxxx b              xxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxx                o    x   ",
   "x          xxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxx              x!!!!!x         x                     x   ",
   "xxxxxxx!!!!x                                                        x!!!!!x         x b                   x   ",
   "      x!!!!x                                                        x!!!!!x         xxxxxxxxxxxxxxxxxxxxxxx   ",
   "      xxxxxx                                                        xxxxxxx                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
